import:
  - ~/.config/catppuccin/catppuccin-latte.yml

env:
  TERM: xterm-256color

window:
  opacity: 0.9

font:
  size: 20

  normal:
    family: Fira Code Nerd Font
    style: Retina

  bold:
    family: Fira Code Nerd Font

  italic:
    family: Fira Code Nerd Font

  bold_italic:
    family: Fira Code Nerd Font
