version = 3
final_space = true

[secondary_prompt]
template = " "
foreground = "p:closer"
background = "transparent"

[transient_prompt]
template = " "
background = "transparent"
foreground_templates = ["{{ if eq .Code 0 }}p:closer{{ else }}p:maroon{{ end }}"]

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

[[blocks.segments]]
template = "{{ .Icon }} "
foreground = "p:os"
background = "transparent"
type = "os"
style = "plain"

[blocks.segments.properties]
cache_duration = "none"

[[blocks.segments]]
template = "{{ .UserName }}@{{ .HostName }} "
foreground = "p:blue"
background = "transparent"
type = "session"
style = "plain"

[blocks.segments.properties]
cache_duration = "none"

[[blocks.segments]]
template = "{{ .Path }} "
foreground = "p:pink"
background = "transparent"
type = "path"
style = "plain"

[blocks.segments.properties]
cache_duration = "none"
home_icon = "~"
style = "folder"

[[blocks.segments]]
template = "{{ .HEAD }}"
foreground = "p:lavender"
background = "transparent"
type = "git"
style = "plain"

[blocks.segments.properties]
branch_icon = " "
cache_duration = "none"
cherry_pick_icon = " "
commit_icon = " "
fetch_status = false
fetch_upstream_icon = false
merge_icon = " "
no_commits_icon = " "
rebase_icon = " "
revert_icon = " "
tag_icon = " "

[[blocks]]
type = "rprompt"
overflow = "hidden"

[[blocks.segments]]
template = "{{ div .Ms 1000 }}s"
foreground = "p:yellow"
background = "transparent"
type = "executiontime"
style = "plain"

[blocks.segments.properties]
cache_duration = "none"
threshold = 5000

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

[[blocks.segments]]
template = ""
background = "transparent"
type = "text"
style = "plain"
foreground_templates = ["{{ if eq .Code 0 }}p:closer{{ else }}p:maroon{{ end }}"]

[blocks.segments.properties]
cache_duration = "none"
